mybatis-plus:
  type-aliases-package: cn.nicollcheng.canal.entity
  mapper-locations: classpath:mapper/*.xml
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cache?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: 192.168.0.51
    port: 6379
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: user-service-provider
canal:
  server: 127.0.0.1:11111
  destination: example

logging:
  level:
    top.javatool.canal.client.client: OFF