server:
  port: 6868
spring:
  application:
    name: ip-location
ip2region:
  external: true
  index-block-size: 4096
  total-header-size: 8192
  location: D:\SimpleCode\java-all-in-one\ip-location\ip2region\data\ip2region.db
  #classpath:ip2region/ip2region.db