server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.0.59:3307/warehouse?characterEncoding=utf8
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: warehouse-service
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
#producer
rocketmq:
  name-server: 192.168.0.51:9876